# planning/ is not a Python package (this file is vendored into consumers' planning/)
"""Generate the planning index from frontmatter.

Run via ``just index``. Globs ``planning/deferred/*.md``, reads their
frontmatter, and prints a Markdown listing of the open queue to stdout,
newest-first. Never writes a file: the listing is a query over the files, not a
committed artifact.

``date`` and ``slug`` are derived from the file name, not frontmatter — the name
is the single source of truth for both.

Decisions are not indexed here. They live in ``docs/adr/`` as numbered ADRs,
where the directory listing is the index and ``docs/adr/check.py`` is the gate.
"""

import pathlib
import re
import sys


ROOT = pathlib.Path(__file__).parent
DEFERRED_RE = re.compile(r"^(?P<date>\d{4}-\d{2}-\d{2})-(?P<slug>.+)$")
DEFERRED_REQUIRED = ("summary",)


def parse_frontmatter(text: str) -> dict[str, str]:
    """Parse a single-line-scalar YAML frontmatter block into a dict."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}
    fields: dict[str, str] = {}
    for line in lines[1:]:
        if line.strip() == "---":
            break
        if line[:1] in (" ", "\t"):
            continue
        key, sep, value = line.partition(": ")
        if not sep:
            continue
        cleaned = value.strip().strip('"').strip("'")
        fields[key.strip()] = "" if cleaned == "null" else cleaned
    return fields


def _named(fields: dict[str, str], name: str, pattern: re.Pattern[str]) -> dict[str, str]:
    """Inject ``date``/``slug`` derived from a file name into ``fields``."""
    match = pattern.match(name)
    if match:
        fields["date"] = match.group("date")
        fields["slug"] = match.group("slug")
    return fields


def load_deferred(root: pathlib.Path) -> list[dict[str, str]]:
    """Read each deferred item's summary; derive date/slug from the file name."""
    deferred_dir = root / "deferred"
    deferred: list[dict[str, str]] = []
    if not deferred_dir.is_dir():
        return deferred
    for path in sorted(deferred_dir.glob("*.md")):
        if path.name == "README.md" or path.name.startswith(("_", ".")):
            continue
        fields = _named(parse_frontmatter(path.read_text(encoding="utf-8")), path.stem, DEFERRED_RE)
        fields["path"] = f"deferred/{path.name}"
        fields["name"] = path.stem
        deferred.append(fields)
    return deferred


def format_row(row: dict[str, str]) -> str:
    """Render one deferred item as a Markdown list item."""
    slug = row.get("slug", "?")
    path = row.get("path", "")
    date = row.get("date", "")
    summary = row.get("summary") or "(no summary)"
    return f"- **[{slug}]({path})** ({date}) — {summary}"


def render(deferred: list[dict[str, str]]) -> str:
    """Render the Markdown listing of the deferred queue, newest-first."""
    out = ["# Planning index", "", "_Generated by `just index` — do not edit._", "", "## Deferred", ""]
    deferred_rows = sorted(deferred, key=lambda b: b.get("name", ""), reverse=True)
    out += [format_row(b) for b in deferred_rows] if deferred_rows else ["_None._"]
    out.append("")
    return "\n".join(out).rstrip() + "\n"


def _require(fields: dict[str, str], keys: tuple[str, ...], rel: str, violations: list[str]) -> None:
    """Append a violation for each required key that is absent or empty."""
    violations.extend(f"{rel}: missing or empty frontmatter key '{key}'" for key in keys if not fields.get(key))


def _check_deferred(path: pathlib.Path, violations: list[str]) -> None:
    """Validate one deferred item (requires `summary` + a revisit trigger)."""
    rel = f"deferred/{path.name}"
    if DEFERRED_RE.match(path.stem) is None:
        violations.append(f"{rel}: file name is not 'YYYY-MM-DD-slug.md'")
    text = path.read_text(encoding="utf-8")
    _require(parse_frontmatter(text), DEFERRED_REQUIRED, rel, violations)
    if "Revisit trigger" not in text:
        violations.append(
            f"{rel}: no '**Revisit trigger:**' section — an item with no trigger is abandoned, not deferred"
        )


def check(root: pathlib.Path) -> list[str]:
    """Validate every deferred item; return the list of violation strings."""
    violations: list[str] = []
    deferred_dir = root / "deferred"
    if deferred_dir.is_dir():
        for path in sorted(deferred_dir.iterdir()):
            if path.name == "README.md" or path.name.startswith(("_", ".")):
                continue
            if path.suffix != ".md":
                violations.append(f"deferred/{path.name}: unexpected non-md file in deferred/")
            else:
                _check_deferred(path, violations)
    return violations


def main(argv: list[str] | None = None, root: pathlib.Path | None = None) -> int:
    """Print the listing to stdout, or validate deferred items with --check."""
    argv = sys.argv[1:] if argv is None else argv
    root = ROOT if root is None else root
    if "--check" in argv:
        violations = check(root)
        if violations:
            sys.stderr.write(f"planning: {len(violations)} violation(s)\n")
            for violation in violations:
                sys.stderr.write(f"  - {violation}\n")
            return 1
        sys.stdout.write("planning: OK\n")
        return 0
    sys.stdout.write(render(load_deferred(root)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
