"""chat type native enum.

Revision ID: fa15d87677c3
Revises: 1be68642e392
Create Date: 2026-08-21 18:45:32.661982

"""

import sqlalchemy as sa
from alembic import op


revision = "fa15d87677c3"
down_revision = "1be68642e392"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("direct", "group", name="chattype").create(op.get_bind())
    op.alter_column(
        "chats",
        "chat_type",
        existing_type=sa.VARCHAR(length=6),
        type_=sa.Enum("direct", "group", name="chattype"),
        existing_nullable=False,
        postgresql_using="chat_type::chattype",
    )
    op.drop_constraint(op.f("ck_chats_chattype"), "chats", type_="check")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        op.f("ck_chats_chattype"),
        "chats",
        "chat_type::text = ANY (ARRAY['direct'::character varying, 'group'::character varying]::text[])",
    )
    op.alter_column(
        "chats",
        "chat_type",
        existing_type=sa.Enum("direct", "group", name="chattype"),
        type_=sa.VARCHAR(length=6),
        existing_nullable=False,
    )
    sa.Enum("direct", "group", name="chattype").drop(op.get_bind())
    # ### end Alembic commands ###
