"""messages.

Revision ID: 1be68642e392
Revises: 88ba0ea3f7e6
Create Date: 2026-08-21 11:09:52.596868

"""

import advanced_alchemy
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "1be68642e392"
down_revision = "88ba0ea3f7e6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("chat_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("idempotency_key", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("created_at", advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("edited_at", advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=True),
        sa.Column("deleted_at", advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], name=op.f("fk_messages_chat_id_chats")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_messages_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        sa.UniqueConstraint("chat_id", "idempotency_key", name="uk_messages_chat_id_idempotency_key"),
    )
    op.create_index("ix_messages_chat_id_id", "messages", ["chat_id", "id"], unique=False)
    op.create_index(op.f("ix_messages_user_id"), "messages", ["user_id"], unique=False)
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed `op.drop_constraint(op.f('ck_chats_chattype'), 'chats', type_='check')`
    # here. That's a known Alembic false positive for `sa.Enum(native_enum=False, create_constraint=True)`
    # columns: Postgres reflects the CHECK constraint body back as `chat_type::text = ANY (ARRAY[...])`,
    # which never textually matches what Alembic renders from the model, so every autogenerate run
    # "detects" this same constraint as removed even though nothing about `chats.chat_type` changed.
    # Dropping it here would be unrelated to this migration's purpose (adding `messages`) and would
    # silently remove enum validation from `chats.chat_type`, so it is intentionally omitted.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_messages_user_id"), table_name="messages")
    op.drop_index("ix_messages_chat_id_id", table_name="messages")
    op.drop_table("messages")
    # ### end Alembic commands ###
