"""chats_and_members.

Revision ID: 88ba0ea3f7e6
Revises: b8565e6bbe4b
Create Date: 2026-08-21 10:09:23.876506

"""

import advanced_alchemy
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "88ba0ea3f7e6"
down_revision = "b8565e6bbe4b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chats",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "chat_type",
            sa.Enum("direct", "group", name="chattype", native_enum=False, create_constraint=True),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=128), nullable=True),
        sa.Column("created_by_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("last_message_id", sa.BigInteger(), nullable=True),
        sa.Column("direct_key", sa.String(length=64), nullable=True),
        sa.Column("created_at", advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], name=op.f("fk_chats_created_by_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chats")),
        sa.UniqueConstraint("direct_key", name=op.f("uq_chats_direct_key")),
    )
    op.create_table(
        "chat_members",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("chat_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("last_read_message_id", sa.BigInteger(), nullable=True),
        sa.Column("joined_at", advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], name=op.f("fk_chat_members_chat_id_chats")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_chat_members_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_members")),
        sa.UniqueConstraint("chat_id", "user_id", name="uk_chat_members_chat_id_user_id"),
    )
    op.create_index(op.f("ix_chat_members_user_id"), "chat_members", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chat_members_user_id"), table_name="chat_members")
    op.drop_table("chat_members")
    op.drop_table("chats")
    # ### end Alembic commands ###
